# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_l
  joint_model_group_pose: p1l
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - d1
    - d2
    - d3
    - d4
    - d5
    - d6
    - i1
    - i2
    - i3
    - i4
    - i5
    - i6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_l_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - i1
    - i2
    - i3
    - i4
    - i5
    - i6
  gains:
    i1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_r_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - d1
    - d2
    - d3
    - d4
    - d5
    - d6
  gains:
    d1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1